### ISSUE TITLE
 defectors have no sense of social acceptability (they are naked why they die)

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#83]
![20230428110324_1](https://user-images.githubusercontent.com/128126252/235039035-6082edfb-7241-46ee-b0bf-cf0db9323d0d.jpg)

additionally they don't despawn when dead and just hang around solitude or windhelm

**Comment by schofida** [comment]
This should be fixed in https://github.com/schofida/CWORR/releases/tag/v1.0.10a

**Comment by schofida** [comment]
As an aside, the number of issues (not that I mind, these are invaluable) are becoming difficult to manage. So I am closing these when I push a fix. But please re-open if you see that the issue persists.

**Comment by LABWAZHERE** [comment]
i can't reopen stuff i didn't close

**Comment by ds-nscorp** [comment]
Ah crap. I didn't know that. Let me know if something still doesn't  work and I'll reopen.

**Comment by LABWAZHERE** [comment]
yes i will
